topdir         := ../..
user_target    := lib
user_rtime_env := user
user_build_dir :=

user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.hpp)
user_no_style  := \
       data_obj.h       \
       ObjLoc.h         \
       ObjMeta.h        \
       ObjRank.h        \
       ObjStats.h       \
       policy_rpc.h     \
       policy_tier.h    \
       SmObjDb.h        \
       sm-platform.h    \
       stor_mgr_err.h   \
       stor_mgr.h       \
       StorMgr.h        \
       StorMgrVolumes.h \
       TierEngine.h     \
       TierPutAlgorithms.h 

include $(topdir)/Makefile.incl
