topdir         := ../..
user_target    := lib
user_rtime_env := user
user_build_dir :=

user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.hpp)
user_no_style  := \

include $(topdir)/Makefile.incl
