topdir         := ../..
user_target    := lib
user_rtime_env := user
user_build_dir :=
user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.h)
user_no_style  := \
        DataMgr.h                \
        data_mgr_pvt.h           \
        data_mgr_transactions.h  \
        dm-platform.h            \
        dm.h                     \
        DmIoReq.h                     

include $(topdir)/Makefile.incl
