#ifndef __FDS_DMGR_H

#define __FDS_DMGR_H

//#define FDS_DMGR_SVR_PORT 11148
#define FDS_DMGR_SVR_PORT 9601

#define FDS_DMGR_MAX_REQ_SZ 16384

enum {
  FDS_DMGR_CMD_NOOP,
  FDS_DMGR_CMD_LOAD_VOLUME,
  FDS_DMGR_CMD_OPEN_TXN,
  FDS_DMGR_CMD_COMMIT_TXN,
  FDS_DMGR_CMD_CANCEL_TXN,
  FDS_DMGR_CMD_MODIFY_AND_COMMIT_TXN,
  FDS_DMGR_CMD_REDIRECT_READ,
  FDS_DMGR_CMD_REDIRECT_OFFSET_WRITE,
  FDS_DMGR_CMD_LAST =  FDS_DMGR_CMD_REDIRECT_OFFSET_WRITE
};


#endif
