#!/bin/bash

MY_DIR="$(dirname "${0}")"
FDS_SRC="${MY_DIR}"/../../..
# FIXME: We should really be getting this from the install.
JAVA_LIB="${FDS_SRC}"/Build/linux-x86_64.debug/lib/java
CLASSPATH="${CLASSPATH}":"${JAVA_LIB}"/\*

java -classpath $CLASSPATH \
     -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=y,address=4050 \
     com.formationds.fdsdiff.Main "${@}"
