#!/bin/bash

for i in /fds/lib/java/\* ; do {
    CLASSPATH=$CLASSPATH:$i;
} done

CLASSPATH=$CLASSPATH

/opt/fds-deps/embedded/jre/bin/java -classpath $CLASSPATH \
     com.formationds.util.TrafficGen $*

