topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_build_dir    :=
user_incl_dir     := $(topdir) ../include
user_cpp_flags    :=
user_cpp          := \
	dm-platform.cpp \
    dm-node-workflow.cpp

user_ar_libs      := fds-dm-plat
fds-dm-plat       := $(user_cpp)

include $(topdir)/Makefile.incl
