<?php
/*
 * Created on Nov 29, 2007
 */
 $COLORS['RED'] = "#ff3333";
 $COLORS['YELLOW'] = "#ffff00";
 $COLORS['PASTEY'] = "#b1d54f";   # Pale Yellow...
 $COLORS['PORANGE'] = "#ecb445";  # Pale Orange...
 $COLORS['GREEN'] = "#00ff00";
 $COLORS['BLUE'] = "#0000ff";
 $COLORS['LIGHTBLUE'] = "#00fff0";
 $COLORS['WHITE'] = "#ffffff";
 $COLORS['GREY'] = "#777777";
 
 $STCOLOR['PASS'] = $COLORS['GREEN'];
 $STCOLOR['FAIL'] = $COLORS['RED'];
 $STCOLOR['SKIP'] = $COLORS['PASTEY'];
 $STCOLOR['XFAIL'] = $COLORS['PORANGE'];
 $STCOLOR['RUNNING'] = $COLORS['YELLOW'];
?>
