topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := $(wildcard *.cpp)
user_no_style    := $(user_cpp)
user_ar_libs     := fds-util
user_so_libs     := fds-util
fds-util         := $(user_cpp)

include $(topdir)/Makefile.incl
