topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := $(wildcard *.cpp)
user_ar_libs     := fds-lib
user_so_libs     := fds-blob
fds-lib          := $(user_cpp)
fds-blob         := $(user_cpp)

user_no_style    :=

include $(topdir)/Makefile.incl
