probe_topdir      := ..
user_fds_so_libs  :=
user_fds_ar_libs  := \
    fds-dsk-mgnt \
    fds-dsk-io

user_non_fds_libs :=

user_cpp          := \
    sm_probe_test.cpp

user_bin_exe      := sm_blk_probe
sm_blk_probe      := sm_probe_test.cpp

include $(probe_topdir)/Makefile.blk
