probe_topdir      := ..
user_fds_so_libs  :=
user_fds_ar_libs  :=

user_non_fds_libs :=

user_cpp          := \
    pm_probe_test.cpp

user_bin_exe      := pm_blk_probe
pm_blk_probe      := pm_probe_test.cpp

include $(probe_topdir)/Makefile.blk
