topdir           := ..
user_target      := lib
user_rtime_env   := user
speedup          = -j $(threads)
user_build_dir   := include endpoint svc_request
user_incl_dir    :=

include $(topdir)/Makefile.incl
