topdir           := ..
include $(topdir)/Makefile.cpus
user_target      := lib
user_rtime_env   := user
speedup          := -j $(parallel_build_count)
user_build_dir   := include endpoint svc_request
user_incl_dir    :=

include $(topdir)/Makefile.incl
