topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := \
    ../include \
    $(topdir)/am-engine

user_cpp         := \
    s3-probe.cpp

user_ar_libs     := fds-probe
fds-probe        := $(user_cpp)

include $(topdir)/Makefile.incl
