topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := $(wildcard *.cpp)
user_ar_libs     := fds-lib
user_so_libs     := fds-crypto
fds-lib          := $(user_cpp)
fds-crypto       := $(user_cpp)

user_no_style    :=
user_incl_dir    :=

include $(topdir)/Makefile.incl
