topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := $(wildcard *.cpp)
user_ar_libs     := fds-lib
fds-lib          := $(user_cpp)

user_no_style    :=
user_incl_dir    := /usr/include/cryptopp

include $(topdir)/Makefile.incl
