topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := $(wildcard *.cpp)
user_so_libs     := fds-lib
fds-lib          := $(user_cpp)

user_no_style    :=
user_incl_dir    :=

include $(topdir)/Makefile.incl
