topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_build_dir    :=
user_incl_dir     := ../include $(topdir)
user_hh           := $(wildcard *.h)
user_cpp          := $(wildcard *.cpp)
user_ar_libs      := fds-om-lib
fds-om-lib        := $(user_cpp)
#user_no_style     := $(user_cpp)
include $(topdir)/Makefile.incl
