topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := \
    fds_resource.cpp

user_ar_libs     := fds-umod
fds-umod         := $(user_cpp)

include $(topdir)/Makefile.incl
