topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := ../include
user_cpp         := \
    pm-probe.cpp \
    sm-probe.cpp

user_ar_libs     := fds-probe
fds-probe        := $(user_cpp)

include $(topdir)/Makefile.incl
