topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_build_dir    :=
user_incl_dir     := $(topdir) ../include
user_cpp_flags    :=
user_cpp          := \
	sm-platform.cpp \
    sm-node-workflow.cpp

user_ar_libs      := fds-sm-plat
fds-sm-plat       := $(user_cpp)

include $(topdir)/Makefile.incl
