#!/bin/bash


for i in ../lib/java/om-1.0-bin/om-1.0/* ; do {
    CLASSPATH=$CLASSPATH:$i ;
} done

CLASSPATH=$CLASSPATH:../lib/java/classes

java -Dfds.config=file:///fds-root/etc/app.properties \
     -classpath $CLASSPATH \
     com.formationds.web.om.Main $*
