topdir           := ..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    :=
user_cpp         :=               \
    vol_policy_clnt.cpp           \
    vol_policy_serv.cpp

user_ar_libs     := fds-netproxy
fds-netproxy     := $(user_cpp)

include $(topdir)/Makefile.incl
