topdir           := ..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    :=
user_cc          := \
    am-plugin.c

user_cpp         :=               \
    am-engine.cpp

user_ar_libs     := fds-am-engine
fds-am-engine    := $(user_cpp) $(user_cc)

include $(topdir)/Makefile.incl
