#!/bin/bash
#
# Perform necessary fds-deps setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Setting up gmond..."
ln -sf /opt/fds-deps/embedded/etc/init/gmond.conf /etc/init/gmond.conf || error_exit "Cannot link gmond upstart config"
chown root:root /etc/init/gmond.conf || error_exit "Cannot set ownership of gmond upstart config"
id -u ganglia > /dev/null || useradd -c "ganglia gmond user" -U -M -r -s /bin/false ganglia || error_exit "Cannot create ganglia user"
initctl reload-configuration

ln -sf /opt/fds-deps/embedded/etc/init/gmond-influxdb-bridge.conf /etc/init/gmond-influxdb-bridge.conf || error_exit "Cannot link gmond-influxdb-bridge upstart config"
chown root:root /etc/init/gmond-influxdb-bridge.conf || error_exit "Cannot set ownership of gmond-influxdb-bridge upstart config"
initctl reload-configuration

echo "Thank you for installing fds-deps!"

exit 0
