#!/bin/bash
#
# Perform necessary fds-deps setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

service gmond stop || echo "Couldn't stop service gmond"
service gmond-influxdb-bridge stop || echo "Couldn't stop service gmond-influxdb-bridge"

exit 0
