topdir          := $(libconfig_dir)/..
user_ext_build  := true

user_no_style   += $(user_cc) $(user_cpp)
user_incl_dir   += \
    $(libconfig_dir)

user_cpp_flags  +=
user_cc_flags   += \
     -DHAVE_CONFIG_H -I. -I.. -DPARSER_PREFIX=\"libconfig_yy\" -D_REENTRRANT \
     -g -O2 -Wall -Wshadow -Wextra -Wdeclaration-after-statement -Wno-unused-parameter

include $(topdir)/Makefile.incl
