topdir         := ..
user_ext_build := true
user_target    := lib
user_rtime_env := user
user_incl_dir  :=
user_cc_flags  :=  -W -Wstrict-prototypes -Wwrite-strings
user_cpp       := \
    $(wildcard *.cpp)

user_no_style  := $(user_cpp)
user_ar_libs   := cryptopp
cryptopp   := $(user_cpp)

include $(topdir)/Makefile.incl
