topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := ../include /usr/include/fuse
user_cpp         :=               \
    cuse_probe.cpp

user_ar_libs     := fds-probe-blk
fds-probe-blk    := $(user_cpp)

include $(topdir)/Makefile.incl
