topdir            := ../..
include $(topdir)/Makefile.cpus
speedup           := -j $(parallel_build_count)
user_build_dir    := handler hvcore
user_incl_dir     := ../include

include $(topdir)/Makefile.incl
