topdir         := ../../..
user_target    := lib
user_rtime_env := user
user_build_dir :=

user_incl_dir  := $(topdir)/stor-mgr/include

user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.hpp)

include $(topdir)/Makefile.incl
