topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_install_loc  :=
user_install      :=

user_incl_dir     :=
user_cpp_flags    :=
user_cpp          :=                   \
    odb.cpp

user_no_style     := $(user_cpp)
user_ar_libs      := fds-odb
user_so_libs      := fds-odb
fds-odb           := $(user_cpp)

include $(topdir)/Makefile.incl
