topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_build_dir    :=
user_incl_dir     := ../include
user_hh           := $(wildcard *.h)
user_cpp          := \
    domain.cpp

user_ar_libs      := fds-om-lib
fds-om-dlt        := $(user_cpp)

include $(topdir)/Makefile.incl
