topdir         := ..
user_ext_build := true
user_target    := lib
user_rtime_env := user
user_incl_dir  :=
user_cc_flags  :=  -W -Wstrict-prototypes -Wwrite-strings
user_cc        := \
        async.c  dict.c  hiredis.c  net.c  sds.c  

user_no_style  := $(uer_cc)
user_ar_libs   := hiredis
hiredis        := $(user_cc)

include $(topdir)/Makefile.incl
