topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_cpp         :=               \
    dm_service.cpp

user_ar_libs     := fds-dsk-mgnt
user_so_libs     := fds-dsk-mgnt
fds-dsk-mgnt     := $(user_cpp)

include $(topdir)/Makefile.incl
