topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := $(topdir) . ../include
user_cpp         := \
	Replica.cpp

user_ar_libs     := fds-replica
fds-replica  := $(user_cpp) $(user_cc)

include $(topdir)/Makefile.incl
