AWS_USER = 'fds_testing'
AWS_PASSWORD = 'bIEYKCPzDKtQDDBomnAKTKRA'
AWS_ACCESS_KEY = "AKIAJAWXAU57VVTDDWAA"
AWS_SECRET_KEY = "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"

AWS_IMAGE = 'ami-1fa78f2f'
AWS_INSTANCE_TYPE = 'm3.medium'
AWS_REGION = 'us-west-2'
AWS_ZONE = 'us-west-2c'
AWS_GROUP_ID = 'sg-43b9c126'