topdir            := $(probe_topdir)/../..
user_target       := test
user_rtime_env    := user

user_incl_dir     += \
    $(topdir)/fds-probe/include \
    $(topdir)/am-engine

user_cpp_flags    +=
user_fds_so_libs  +=
user_fds_ar_libs  +=  \
    fds-probe-blk \
    fds-probe \
    fds-dsk-io \
    fds-dsk-mgnt \
    fds-fdsp \
    fds-lib \
    fds-umod \
    fds-util \
    fds-thread \
    fds-osdep

user_non_fds_libs +=  \
    boost_log \
    boost_system \
    boost_thread \
    boost_date_time \
    boost_program_options \
    boost_timer \
    jansson \
    fuse \
    thrift \
    config++ \
    fiu \
    dl

include $(topdir)/Makefile.incl
