topdir            := ../..
speedup           := -j 7
user_build_dir    := s3 thrift pm sm \
    s3-template  \
    blk-template \
    threadpool   \
    fds-net      \
    stor-mgr     \
    stor-mgr-full\
    data-mgr     \
    orch-mgr     \
    platform     \
    mock-server

include $(topdir)/Makefile.incl
