topdir            := ../..
user_target       := lib
user_rtime_env    := user
user_build_dir    :=
user_incl_dir     := ../include
user_hh           := $(wildcard *.h)
user_cpp          := \
    om-service.cpp

user_ar_libs      := fds-om-common
fds-om-common     := $(user_cpp)

include $(topdir)/Makefile.incl
