/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_formationds_om_NativeOm */

#ifndef _Included_com_formationds_om_NativeOm
#define _Included_com_formationds_om_NativeOm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_formationds_om_NativeOm
 * Method:    init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_formationds_om_NativeOm_init
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
