topdir         := ../..
user_target    := lib
user_rtime_env := user
user_build_dir := dm-vol-cat dm-tvc
user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.h)

include $(topdir)/Makefile.incl
