#!/bin/bash

./bare_am $* &
sleep 1

CLASSPATH=$CLASSPATH:../lib/java/fds-1.0-bin/fds-1.0/\*:../lib/java/classes

instance=$( echo `expr match "$*" '.*platform_port=*\([0-9]\)'` )
port=$(($instance + 4000))
java -classpath $CLASSPATH \
     com.formationds.am.Main $*
