#!/bin/bash

./bare_am $* &
sleep 1

#for i in ../lib/java/fds-1.0-bin/fds-1.0/* ; do {
#    CLASSPATH=$CLASSPATH:$i ;
#} done

CLASSPATH=$CLASSPATH:../lib/java/fds-1.0-bin/fds-1.0/\*:../lib/java/classes

instance=$( echo `expr match "$*" '.*Id=*\([0-9]\)'` )
port=$(($instance + 4000))
java -classpath $CLASSPATH \
     -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$port \
     com.formationds.am.Main $*
