#!/bin/bash

for i in ../lib/java/fds-1.0-bin/fds-1.0/* ; do {
    CLASSPATH=$CLASSPATH:$i ;
} done

CLASSPATH=$CLASSPATH:../lib/java/classes

if [ $# -eq 0 ]; then
    echo "Usage: ./smokeTest targetHost"
    exit 1
fi
tgthost=$1
shift
java -classpath $CLASSPATH \
     -Dfds.host=${tgthost} \
     -Dcom.formationds.smoketest.RNG_CLASS=java.util.Random \
     com.formationds.smoketest.SmokeTestRunner "$@"

