topdir         := $(nginx_dir)/..
user_ext_build := true

user_incl_dir  += \
    $(nginx_src_dir)/core \
    $(nginx_src_dir)/event \
    $(nginx_src_dir)/event/modules \
    $(nginx_src_dir)/os/unix \
    $(nginx_src_dir)/http \
    $(nginx_src_dir)/http/modules \
    $(nginx_src_dir)/mail \
    $(nginx_dir)/objs

user_no_style  += $(user_cpp) $(user_cc)
user_cc_flags  += \
    -pipe -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g \
    -O3

include $(topdir)/Makefile.incl
