thrift_dir       := ../../../..
user_taget       := lib
user_rtime_env   := user
user_incl_dir    :=
user_cc_flags    :=
user_cpp         := \
    parse.cc

user_no_style    := $(user_cc) $(user_cpp)
user_ar_libs     := thrift-parse
thrift-parse     := $(user_cc) $(user_cpp)

include $(thrift_dir)/Makefile.incl
