/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_formationds_util_Bootstrapper */

#ifndef _Included_com_formationds_util_Bootstrapper
#define _Included_com_formationds_util_Bootstrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_formationds_util_Bootstrapper
 * Method:    printf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_formationds_util_Bootstrapper_printf
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
