/*
 * Copyright (c) 2014, Formation Data Systems, Inc. All Rights Reserved.
 */

package com.formationds.commons.events.annotation;

import com.formationds.commons.events.EventCategory;
import com.formationds.commons.events.EventSeverity;
import com.formationds.commons.events.EventType;

import java.lang.annotation.*;

/**
 * TODO: what is the default message key naming strategy if a message key is not specified.
 */
@Documented
@Inherited
@Target( { ElementType.METHOD } )
@Retention( RetentionPolicy.RUNTIME )
public @interface Event {

    /**
     * Specify the type of event generated by the associated method invocation
     *
     * @return
     */
    EventType type();

    /**
     * The event category
     * @return
     */
    EventCategory category();

    /**
     * The event severity
     *
     * @return
     */
    EventSeverity severity();

    /**
     * The message key.  If not specified the default message key naming strategy (TBD) is used.
     *
     * @return
     */
    String key() default "";

    /**
     * There are two ways to specify EventArgs: (1) within the Event annotation in an args list; (2)
     * as @EventArgs annotations on method parameters.  In general, including them on the method
     * parameters is preferred because it makes it clearer when refactoring methods.
     * @return
     */
    EventArg[] args() default {};
}
