topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_incl_dir    := ../include

user_cpp         := \
    platform.cpp

user_ar_libs     := fds-plat-common
fds-plat-common  := $(user_cpp)

include $(topdir)/Makefile.incl
