topdir           := ../../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := \
	$(topdir)/platform/include \
	$(topdir)/net-service/include

user_cc          :=
user_cpp         :=

user_ar_libs     := fds-probe-ut
fds-probe-ut     := $(user_cpp) $(user_cc)

include $(topdir)/Makefile.incl
