topdir         := ../../..
user_target    := lib
user_rtime_env := user
user_build_dir :=
user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.h)

user_no_style  := copy_env.h

include $(topdir)/Makefile.incl
