topdir         := ..
user_ext_build := true
user_target    := lib
user_rtime_env := user
user_incl_dir  :=
user_cc_flags  :=  -Wall
user_cc        := $(wildcard *.c)
user_cpp       := $(wildcard *.cpp)

user_no_style  := $(user_cc) $(user_cpp)
user_ar_libs   := cmdconsole
user_so_libs   := cmdconsole
cmdconsole     := $(user_cc) $(user_cpp)

include $(topdir)/Makefile.incl
