topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_cpp         :=               \
    dm_read.cpp                   \
    dm_write.cpp

user_ar_libs     := fds-dsk-io
fds-dsk-io       := $(user_cpp)

include $(topdir)/Makefile.incl
