libconfig_dir   := ..
user_target     := lib
user_rtime_env  := user
user_incl_dir   := ..
user_cc         := \
    strbuf.c  \
    libconfig.c \
    scanner.c \
    grammar.c \
    scanctx.c

user_cpp        := \
    libconfigcpp.cpp

user_ar_libs    := config++
config++        := $(user_cc) $(user_cpp)

include $(libconfig_dir)/Makefile.incl
