thrift_dir       := ../../../..
user_taget       := lib
user_rtime_env   := user
user_incl_dir    :=
user_cc_flags    :=
user_cpp         := \
    t_generator.cc \
    t_c_glib_generator.cc \
    t_cpp_generator.cc \
    t_java_generator.cc \
    t_as3_generator.cc \
    t_csharp_generator.cc \
    t_py_generator.cc \
    t_rb_generator.cc \
    t_perl_generator.cc \
    t_php_generator.cc \
    t_erl_generator.cc \
    t_cocoa_generator.cc \
    t_st_generator.cc \
    t_ocaml_generator.cc \
    t_hs_generator.cc \
    t_xsd_generator.cc \
    t_html_generator.cc \
    t_js_generator.cc \
    t_javame_generator.cc \
    t_delphi_generator.cc \
    t_go_generator.cc \
    t_d_generator.cc

user_no_style    := $(user_cc) $(user_cpp)
user_ar_libs     := thrift-genlib
thrift-genlib    := $(user_cc) $(user_cpp)

include $(thrift_dir)/Makefile.incl
