topdir            := $(test_topdir)/..
user_target       := test
user_std_libs     := true
user_rtime_env    := user

user_incl_dir     += \
    $(topdir)/platform/include \
    $(topdir)/stor-mgr/include \
    $(topdir)/stor-mgr/migrations \
    $(topdir)/lib \
    $(topdir)

user_cpp_flags    +=
user_fds_so_libs  +=
user_fds_ar_libs  +=  \
    fds-test \
    fds-smlib \
    fds-am-engine \
    fds-odb \
    fds-sm-plat \
    fds-vpolicy \
    fds-dsk-mgnt \
    fds-dsk-io \
    fds-hash \
    fds-xdi

user_non_fds_libs +=  \
    jansson \
	udev \
	parted \
    crypt \
	pcre \
	crypto \
	z \
	cryptopp \
    ssl \
    boost_timer \
    gmock \
    leveldb \
    profiler

include $(topdir)/Makefile.incl
