topdir            := $(test_topdir)/..
user_target       := test
user_std_libs     := true
user_rtime_env    := user

user_incl_dir     += \
	$(topdir)/platform/include \
	$(topdir)/access-mgr/include \
    $(topdir)

user_cpp_flags    +=
user_fds_so_libs  +=
user_fds_ar_libs  +=  \
    fds-test \
    fds-am-engine \
    fds-dsk-io \
    fds-dsk-mgnt \
    fds-hash \
    fds-fdsp \
    fds-plat-lib

user_non_fds_libs +=  \
    jansson \
	udev \
	parted \
    pthread crypt pcre crypto \
	z \
    ssl \
    gmock \
    leveldb \
    profiler

include $(topdir)/Makefile.incl
