topdir         := ..
speedup        = -j $(threads)
user_build_dir :=      \
    lib                \
    orch-mgr           \
    persistent-layer   \
    umod-lib           \
    util               \
    stor-mgr           \
    data-mgr

include $(topdir)/Makefile.incl
