topdir         := ..
speedup        := -j 5
user_build_dir :=      \
    lib                \
    odb                \
    fds-probe          \
    orch_mgr           \
    persistent_layer   \
    umod-lib           \
    util               \
    data-mgr           \
    dlt                \
    migrations         \
    stor-mgr

include $(topdir)/Makefile.incl
