topdir            := $(test_topdir)/..
user_target       := test
user_std_libs     := true
user_rtime_env    := user

user_incl_dir     += \
    $(topdir)/orch-mgr/include \
    $(topdir)/lib \
    $(topdir)

user_cpp_flags    +=
user_fds_so_libs  +=
user_fds_ar_libs  +=  \
    fds-test \
    fds-om-common \
    fds-om-lib \
    fds-om-dlt \
    fds-plat-lib \
    fds-am-engine \
    fds-hash \
    fds-fdsp

user_non_fds_libs +=  \
    jansson \
	udev \
	parted \
    crypt \
	pcre \
	crypto \
	z \
    ssl \
    boost_timer \
    gmock \
    leveldb \
    profiler \
	pthread \
    ical

include $(topdir)/Makefile.incl
