topdir         := ..
user_target    := lib
user_rtime_env := user
user_build_dir := \
    fdsp \
    am-engine \
    concurrency \
    fds-probe \
    hash \
    ipc \
    json \
    persistent_layer \
    shared \
    util

user_hh        := $(wildcard *.h)
user_hpp       := $(wildcard *.hpp)
user_no_style  := $(user_hh) $(user_hpp)

include $(topdir)/Makefile.incl
