topdir           := ..
speedup          = -j $(threads)
user_build_dir   := \
                    hash \
                    misc \
                    volume-checker
user_incl_dir    := ../include
include $(topdir)/Makefile.incl
