topdir           := ..
user_target      := lib
user_rtime_env   := user
user_build_dir   := hash
user_cpp         := \
    PerfStatHist.cpp Log.cpp

user_ar_libs     := fds-util
fds-util         := $(user_cpp)

include $(topdir)/Makefile.incl
