ifdef user_std_libs
    user_fds_ar_libs += \
        fds-plat-lib \
        fds-net-svc \
        fds-svc-request \
        fds-lib \
        fds-umod \
        fds-util \
        fds-fdsp \
        fds-hash \
        fds-thread \
        fds-osdep

    user_non_fds_libs += \
        boost_log \
        boost_system \
        boost_thread \
        boost_date_time \
        boost_program_options \
        boost_filesystem \
        boost_regex \
        thrift \
        event \
        config++ \
        rt \
        hiredis \
        fiu \
        dl
endif

incl_scripts := $(M)$(topdir)/Build/mk-scripts
include $(incl_scripts)/Makefile.start
