ifdef user_std_libs
    user_fds_ar_libs += \
        fds-plat-lib \
        fds-net-svc \
        fds-svc-request \
        fds-lib \
        fds-umod \
        fds-util \
        fds-fdsp \
        fds-hash \
        fds-thread \
        fds-osdep

	# boost_chrono and rabbitmq are used in the SimpleAmqpClient library
	# The SimpleAmqpClient is used in the statsclient library
    user_non_fds_libs += \
        statsclient \
	SimpleAmqpClient \
	rabbitmq \
        boost_log \
        boost_system \
        boost_thread \
        boost_date_time \
        boost_program_options \
        boost_filesystem \
        boost_regex \
	boost_chrono \
	ssl \
    	crypto \
        thrift \
        event \
        config++ \
        rt \
        hiredis \
        fiu \
        dl

	user_static_libs := ev
endif

incl_scripts := $(M)$(topdir)/Build/mk-scripts
include $(incl_scripts)/Makefile.start

threads = 5
