topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    := ../include /usr/include/fuse
user_cpp         :=               \
    fds_probe.cpp

user_no_style    := $(user_cpp)
user_ar_libs     := fds-probe
fds-probe        := $(user_cpp)

include $(topdir)/Makefile.incl
