topdir            := ../..
user_target       := test
user_rtime_env    := user

user_fds_so_libs  :=
user_fds_ar_libs  := fds-thread
user_non_fds_libs := boost_thread boost_system

user_cpp          := ThreadPoolTest.cpp
user_bin_exe      := threadtest
threadtest        := $(user_cpp)

include $(topdir)/Makefile.incl
