topdir         := ../

# List all directories that builds library first before making exe and unit
# test.
# List one module/line to minimize conflict during merge.
#
user_build_dir := configdb

include $(topdir)/Makefile.incl
