topdir           := ../..
user_target      := lib
user_rtime_env   := user
user_cpp         := \
    FDSP.cpp orch_proto.cpp

user_no_style    := $(user_cpp)
user_ar_libs     := fds-fdsp
fds-fdsp         := $(user_cpp)

include $(topdir)/Makefile.incl
