/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if kernel supports AIO cancel on file descriptor */
/* #undef HAVE_AIO_CANCEL_FD */

/* Define to 1 if kernel supports signal on AIO completion */
/* #undef HAVE_AIO_EVENTS */

/* Define to 1 if kernel supports buffered AIO */
/* #undef HAVE_BUFFERED_AIO */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if kernel supports LIO events */
/* #undef HAVE_LIO_EVENTS */

/* Define to 1 if kernel supports LIO wait */
/* #undef HAVE_LIO_WAIT */

/* Define to 1 if kernel supports io_setup(0,...) */
/* #undef HAVE_MAXEVENTS_DEFAULT */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "libposix-aio"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Sebastien.Dugue@bull.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libposix-aio"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libposix-aio 0.8.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libposix-aio"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.8.1"

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */
