topdir           := ../../
user_target      := lib
user_rtime_env   := user
user_build_dir   :=
user_incl_dir    :=
user_cpp         :=  $(wildcard *.cpp)              
user_ar_libs     := fds-am-engine

include $(topdir)/Makefile.incl
